import Papa from 'papaparse';
import { stringify } from 'csv-stringify/sync';
import { pool, getUserLimits, countUploads } from './db.js';

// Heuristics for locating the email column when the header isn't literally "email".
const EMAIL_HEADER_CANDIDATES = [
  'email', 'e-mail', 'email address', 'email_address',
  'mail', 'e_mail', 'emailaddress',
];

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function detectEmailColumn(fields, sampleRows) {
  // 1. Exact-ish header match.
  for (const f of fields) {
    if (EMAIL_HEADER_CANDIDATES.includes(f.trim().toLowerCase())) return f;
  }
  // 2. Fall back to the column whose sampled values most look like emails.
  let best = null;
  let bestScore = 0;
  for (const f of fields) {
    let hits = 0;
    let seen = 0;
    for (const row of sampleRows) {
      const v = row[f];
      if (v == null || v === '') continue;
      seen++;
      if (EMAIL_RE.test(String(v).trim())) hits++;
    }
    const score = seen ? hits / seen : 0;
    if (score > bestScore && score >= 0.6) {
      best = f;
      bestScore = score;
    }
  }
  return best;
}

export async function processUpload(userId, fileBuffer, filename) {
  const text = fileBuffer.toString('utf8');

  const parsed = Papa.parse(text, {
    header: true,
    delimiter: ',', // pin to comma; auto-detect misfires on single-column files
    skipEmptyLines: 'greedy',
    transformHeader: (h) => h.trim(),
  });

  if (parsed.errors.length) {
    const fatal = parsed.errors.find((e) => e.type === 'Delimiter' || e.code === 'MissingQuotes');
    if (fatal) throw new AppError(`CSV could not be parsed: ${fatal.message}`, 400);
  }

  const rows = parsed.data;
  const fields = parsed.meta.fields || [];

  if (fields.length === 0) throw new AppError('CSV has no header row.', 400);
  if (rows.length === 0) throw new AppError('CSV has no data rows.', 400);

  const { maxUploads, maxRowsPerUpload } = await getUserLimits(userId);

  if (rows.length > maxRowsPerUpload) {
    throw new AppError(
      `This file has ${rows.length} rows. Your limit is ${maxRowsPerUpload} rows per upload.`,
      400
    );
  }

  const emailColumn = detectEmailColumn(fields, rows.slice(0, 50));
  if (!emailColumn) {
    throw new AppError(
      'No email column found. Include a column named "email" (or one containing valid email addresses).',
      400
    );
  }

  // Persist upload + records in a single transaction. UUIDs for each record
  // are generated by Postgres gen_random_uuid() (RFC 4122 v4).
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // Lock this user's row so concurrent uploads can't both pass the cap check.
    // The count and the insert now happen in one serialized critical section.
    await client.query('SELECT id FROM users WHERE id = $1 FOR UPDATE', [userId]);

    const { rows: cnt } = await client.query(
      'SELECT COUNT(*)::int AS n FROM uploads WHERE user_id = $1',
      [userId]
    );
    if (cnt[0].n >= maxUploads) {
      throw new AppError(
        `You've reached your limit of ${maxUploads} uploads. Delete one to add another.`,
        403
      );
    }

    const { rows: up } = await client.query(
      `INSERT INTO uploads (user_id, filename, row_count, email_column, columns)
       VALUES ($1, $2, $3, $4, $5) RETURNING id, created_at`,
      [userId, filename, rows.length, emailColumn, JSON.stringify(fields)]
    );
    const uploadId = up[0].id;

    // Bulk insert records. Chunked to keep parameter counts sane.
    const CHUNK = 500;
    for (let i = 0; i < rows.length; i += CHUNK) {
      const chunk = rows.slice(i, i + CHUNK);
      const values = [];
      const params = [];
      chunk.forEach((row, j) => {
        const base = j * 4;
        values.push(`($${base + 1}, $${base + 2}, $${base + 3}, $${base + 4})`);
        const email = row[emailColumn] != null ? String(row[emailColumn]).trim() : null;
        params.push(uploadId, i + j, email, JSON.stringify(row));
      });
      await client.query(
        `INSERT INTO records (upload_id, row_index, email, data)
         VALUES ${values.join(', ')}`,
        params
      );
    }

    await client.query('COMMIT');
    return { uploadId, rowCount: rows.length, emailColumn, columns: fields };
  } catch (e) {
    await client.query('ROLLBACK');
    throw e;
  } finally {
    client.release();
  }
}

// Build the export CSV: original columns in original order, plus an appended
// `uuid` column. Records are returned in original row order.
export async function exportUpload(userId, uploadId) {
  const { rows: up } = await pool.query(
    `SELECT id, filename, columns FROM uploads WHERE id = $1 AND user_id = $2`,
    [uploadId, userId]
  );
  if (!up[0]) throw new AppError('Upload not found.', 404);

  const columns = up[0].columns;
  const { rows: records } = await pool.query(
    `SELECT id, data FROM records WHERE upload_id = $1 ORDER BY row_index ASC`,
    [uploadId]
  );

  // Avoid clobbering an existing column literally named "uuid".
  let uuidCol = 'uuid';
  if (columns.includes(uuidCol)) uuidCol = 'assigned_uuid';

  const header = [...columns, uuidCol];
  const out = records.map((r) => {
    const line = {};
    for (const c of columns) line[c] = r.data[c] ?? '';
    line[uuidCol] = r.id;
    return line;
  });

  const csv = stringify(out, { header: true, columns: header });
  const safeName = (up[0].filename || 'export').replace(/\.csv$/i, '');
  return { csv, filename: `${safeName}-with-uuid.csv` };
}

export class AppError extends Error {
  constructor(message, status = 400) {
    super(message);
    this.status = status;
  }
}
